### ISSUE TITLE
DICOM thumbnails sometimes do not load

### ISSUE THREAD

**Issue by floryst** [KitwareMedical/VolView#135]
Repro steps:
- Load a local dicom dataset, and load the Abdomen-MRI sample dataset
- expand all studies to show the thumbnails for each volume
- Some thumbnails will not render

The immediate cause is due to `file` being undefined on this line: https://github.com/KitwareMedical/VolView/blob/master/src/io/dicom.ts#L138

**Comment by cjh1** [comment]
I can create this and will take a look
