### ISSUE TITLE
Indicating loaded datasets when dealing with multiple datasets

### ISSUE THREAD

**Issue by sankhesh** [KitwareMedical/VolView#177]
I couldn't figure out a way to unload/reload the data? Unchecking the box in the Data section didn't really remove it from the rendered views.

In the screenshot below, I could delete the data/patient but when I had two datasets loaded, I couldn't switch to the other data or render them simultaneously.

![image1](https://user-images.githubusercontent.com/936354/197777932-15e2e35b-a143-4018-ba67-439d4aaf1798.png)

**Comment by floryst** [comment]
See also #69

**Comment by floryst** [comment]
- Collapsing sample dataset
- highlight the patient line + study line in addition to highlighting the selected volume.
