### ISSUE TITLE
Very difficult to scroll slice by just 1

### ISSUE THREAD

**Issue by jadh4v** [KitwareMedical/VolView#191]
Very hard to change slice by just 1. Single tick scroll doesn't work. Can also add arrow key action for the same.

**Comment by sankhesh** [comment]
I am not sure how this works right now, but I'd imagine that each mouse scroll "tick" should change the slice number by 1.

**Comment by floryst** [comment]
Up-down arrow keys for single-slice scrolling via keyboard.
