### ISSUE TITLE
Cropping is sluggish on 2D views

### ISSUE THREAD

**Issue by jadh4v** [KitwareMedical/VolView#192]
Cropping is sluggish (poor performance) when performed on the 2D slices. But performs much better when directly done on 3D view.

**Comment by aylward** [comment]
Will perhaps try to trigger LoD rendering when doing cropping.   Forrest will investigate.

**Comment by floryst** [comment]
See also #195

**Comment by floryst** [comment]
Investigate: hide 3D view and then try 2D crop to see how data size is affecting lag in the 2D crop interaction.
