### ISSUE TITLE
Add panning for 3D view

### ISSUE THREAD

**Issue by jadh4v** [KitwareMedical/VolView#193]
There is currently no panning action on 3D view. Add panning as it is required to control the view particularly when zoomed in for observing specific features closely.

**Comment by aylward** [comment]
Shift-left button pans.   Right now we are using ParaView default.   Should look at Osirix and other defaults.

We will use and document standard controls.  

See also https://github.com/KitwareMedical/VolView/issues/172

**Comment by x1y9** [comment]
so why not add mouse middle button for panning in 3d view as other views?

**Comment by PaulHax** [comment]
> so why not add mouse middle button for panning in 3d view as other views?

@x1y9 Good question!  Looks like we had that working in https://github.com/Kitware/VolView/pull/232 but we regressed when moving to this: https://github.com/Kitware/VolView/blob/main/src/components/vtk/VtkVolumeView.vue#L67-L71

Could fix by putting this in VtkVolumeView.vue
```
useVtkInteractionManipulator(
  interactorStyle,
  vtkMouseCameraTrackballPanManipulator,
  { button: 2 }
);
```

Care to test that out and open a PR?
