### ISSUE TITLE
Poor volume rendering performance on large datasets

### ISSUE THREAD

**Issue by jadh4v** [KitwareMedical/VolView#195]
Poor volume rendering performance on large datasets (CTA chest). This is understandable, but perhaps more tuning could be done for managing quality <--> performance tradeoff.

For e.g. CTA chest 3D view is very sticky. When trying to rotate the view, it takes a second or two for the view to start responding to the click-drag action. Similarly, a related issue is that LAO kernel size/radius sliders are hard to drag. They should only update the rendering upon mouse button release.

**Comment by aylward** [comment]
Great suggestion: "They should only update the rendering upon mouse button release."
- Either re-render only on release or for a long pause.

**Comment by aylward** [comment]
Will investigate vtk.js support for throttling.

**Comment by floryst** [comment]
Disabling CVR, shading, while animating can help mitigate these perf issues.
