### ISSUE TITLE
Paint bugs and features

### ISSUE THREAD

**Issue by floryst** [KitwareMedical/VolView#72]
- [ ] world-space brush
- [x] lerp between points
- [x] can't click once to erase on axial view with abdomen mri dataset in certain spots. Probably an issue with the determining of whether to paint?
- [x] auto-show annotations pane

**Comment by timthirion** [comment]
@floryst, looks like world space brush might be broken again.

**Comment by floryst** [comment]
Un-checked "world-space brush".
